build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
    - path: out/sldl.zip
      name: Soundcloud-dl $(appveyor_build_version)

deploy:
  release: sldl-v$(appveyor_build_version)
  description: 'Release $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: ZUI/J+KOm2wseKsbRjCliK+mtStCASQFH62eT+iU2HhP7pASL9gFvl6Rt0tdER5o
  artifact: out/sldl.zip           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    # branch: master               # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only